-- MINI questionnaire: Supabase database setup
-- Run this in Supabase SQL Editor.

create table if not exists public.responses (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  submitted_at timestamptz not null default now(),
  project text not null default 'MINI Everyday First Aid Concept',
  language text not null check (language in ('en', 'fr', 'ar')),
  answers jsonb not null check (jsonb_typeof(answers) = 'object'),
  source text
);

alter table public.responses enable row level security;

-- The public questionnaire only needs INSERT permission.
-- Visitors must NOT be able to read everyone else's answers.
revoke all on table public.responses from public, anon, authenticated;
grant insert on table public.responses to anon, authenticated;

-- Required for the identity column when rows are inserted without an id.
grant usage, select on sequence public.responses_id_seq to anon, authenticated;

 drop policy if exists "Public can submit MINI questionnaire" on public.responses;
create policy "Public can submit MINI questionnaire"
on public.responses
for insert
to anon, authenticated
with check (
  project = 'MINI Everyday First Aid Concept'
  and language in ('en', 'fr', 'ar')
  and jsonb_typeof(answers) = 'object'
);

-- IMPORTANT:
-- Do NOT create a public SELECT policy.
-- You can see the responses yourself in Supabase Dashboard > Table Editor > responses.
-- Never put a Supabase secret/service_role key in GitHub Pages/browser code.
